apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-worker
  labels:
    {{- include "banking.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: banking-worker
  template:
    metadata:
      labels:
        app: banking-worker
        component: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.worker.metricsPort }}"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: worker
          image: {{ include "banking.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/workers/transaction.worker.js"]
          ports:
            - containerPort: {{ .Values.worker.metricsPort }}
              name: metrics
          envFrom:
            - configMapRef:
                name: banking-config
            - secretRef:
                name: banking-secret
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.worker.metricsPort }} }
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.worker.metricsPort }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
